### PR TITLE
Midi control assignment

### PR DESCRIPTION
**Pull request by xmacex**
MIDI control assignment. Now such a robust implementation, and macro's aren't implemented because I don't feel confident I understand how they work, but this seems to work.

Thanks for an interesting script, it's fun with with an OP-Z.

### CODE REVIEW

**Comment by justmat** [comment]
thanks for the PR, @xmacex!
one thing i thought about while glancing over, was naming the command "cc" instead of "midi", since we're mapping cc's and not midi notes. that way "midi" as a command is left open for possible midi note things in the future. 

i'll check it out in detail, and run it on my machine tomorrow morning.

**Comment by justmat** [comment]
looks great, and works on on my machine. i really like that you used the pmap system! 

i am going to merge, but i will likely be changing the op name to "cc" instead of "midi". i have some vague plans for a "midi" op :)

**Comment by xmacex** [comment]
Oh yeah, `cc`rather than `midi` makes total sense! I stored the mappings into `midi_choices` for consistency's sake to perhaps be shown in the UI like the `{enc,arc,grid+}_choices` but left that unused. For UI design it's worth noting that these MIDI mappings do not have a specific number of them, like `enc` (3) and `arc` (4) do.

**Comment by justmat** [comment]
for UI, i think i will just fill midi_choices (cc_choices?) with the cc numbers as id's.

**Pull request merged**
